# Google Analytics Revenue Prediction

## Preprocessing

**Environment**

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

# Pandas defaults
pd.options.display.max_columns = 500
pd.options.display.max_rows = 500
 
# Make jupyter bigger
from IPython.core.display import display, HTML
display(HTML('<style>.container { width:100% !important; }</style>'))

In [2]:
from myfunctions import *

**Import Dataframe**

In [3]:
df = pd.read_csv("data/df2.csv", low_memory=False)

### Dataset Analysis

In [4]:
df.shape

(903653, 38)

There are 38 columns and 903653 rows

In [5]:
df.columns

Index(['channelGrouping', 'date', 'fullVisitorId', 'sessionId',
       'socialEngagementType', 'visitId', 'visitNumber', 'visitStartTime',
       'device.browser', 'device.deviceCategory', 'device.isMobile',
       'device.operatingSystem', 'geoNetwork.city', 'geoNetwork.continent',
       'geoNetwork.country', 'geoNetwork.metro', 'geoNetwork.networkDomain',
       'geoNetwork.region', 'geoNetwork.subContinent', 'totals.bounces',
       'totals.hits', 'totals.newVisits', 'totals.pageviews',
       'totals.transactionRevenue', 'totals.visits', 'trafficSource.adContent',
       'trafficSource.adwordsClickInfo.adNetworkType',
       'trafficSource.adwordsClickInfo.gclId',
       'trafficSource.adwordsClickInfo.isVideoAd',
       'trafficSource.adwordsClickInfo.page',
       'trafficSource.adwordsClickInfo.slot', 'trafficSource.campaign',
       'trafficSource.campaignCode', 'trafficSource.isTrueDirect',
       'trafficSource.keyword', 'trafficSource.medium',
       'trafficSource.referral

Rename the columns with more friendly names

In [6]:
df.columns = ['channelGrouping', 'date', 'fullVisitorId', 'sessionId',
       'socialEngagementType', 'visitId', 'visitNumber', 'visitStartTime',
       'deviceBrowser', 'deviceCategory', 'deviceIsMobile',
       'deviceOS', 'geoCity', 'geoContinent',
       'geoCountry', 'geoMetro', 'geoDomain',
       'geoRegion', 'geoSubContinent', 'totalsBounces',
       'totalsHits', 'totalsNewVisits', 'totalsPageviews',
       'totalsTransactionRevenue', 'totalsVisits', 'trafficSourceAdContent',
       'adwordsClickAdNetworkType',
       'adwordsClickGclId',
       'adwordsClickIsVideoAd',
       'adwordsClickInfoPage',
       'adwordsClickInfoSlot', 'trafficSourceCampaign',
       'trafficSourceCampaignCode', 'trafficSourceIsTrueDirect',
       'trafficSourceKeyword', 'trafficSourceMedium',
       'trafficSourceReferralPath', 'trafficSourceSource']

In [7]:
df.head()

channelGrouping      date        fullVisitorId  \
0  Organic Search  20160902  1131660440785968503   
1  Organic Search  20160902   377306020877927890   
2  Organic Search  20160902  3895546263509774583   
3  Organic Search  20160902  4763447161404445595   
4  Organic Search  20160902    27294437909732085   

                        sessionId  socialEngagementType     visitId  \
0  1131660440785968503_1472830385  Not Socially Engaged  1472830385   
1   377306020877927890_1472880147  Not Socially Engaged  1472880147   
2  3895546263509774583_1472865386  Not Socially Engaged  1472865386   
3  4763447161404445595_1472881213  Not Socially Engaged  1472881213   
4    27294437909732085_1472822600  Not Socially Engaged  1472822600   

   visitNumber  visitStartTime deviceBrowser deviceCategory  deviceIsMobile  \
0            1      1472830385        Chrome        desktop           False   
1            1      1472880147       Firefox        desktop           False   
2            1      1472865386        Chrome        desktop           False   
3            1      1472881213    UC Browser        desktop           False   
4            2      1472822600        Chrome         mobile            True   

    deviceOS geoCity geoContinent      geoCountry geoMetro        geoDomain  \
0    Windows   Izmir         Asia          Turkey      NaN     ttnet.com.tr   
1  Macintosh     NaN      Oceania       Australia      NaN      dodo.net.au   
2    Windows  Madrid       Europe           Spain      NaN  unknown.unknown   
3      Linux     NaN         Asia       Indonesia      NaN  unknown.unknown   
4    Android     NaN       Europe  United Kingdom      NaN  unknown.unknown   

             geoRegion  geoSubContinent  totalsBounces  totalsHits  \
0                Izmir     Western Asia            1.0           1   
1                  NaN      Australasia            1.0           1   
2  Community of Madrid  Southern Europe            1.0           1   
3                  NaN   Southeast Asia            1.0           1   
4                  NaN  Northern Europe            1.0           1   

   totalsNewVisits  totalsPageviews  totalsTransactionRevenue  totalsVisits  \
0              1.0              1.0                       NaN             1   
1              1.0              1.0                       NaN             1   
2              1.0              1.0                       NaN             1   
3              1.0              1.0                       NaN             1   
4              NaN              1.0                       NaN             1   

  trafficSourceAdContent adwordsClickAdNetworkType adwordsClickGclId  \
0                    NaN                       NaN               NaN   
1                    NaN                       NaN               NaN   
2                    NaN                       NaN               NaN   
3                    NaN                       NaN               NaN   
4                    NaN                       NaN               NaN   

  adwordsClickIsVideoAd  adwordsClickInfoPage adwordsClickInfoSlot  \
0                   NaN                   NaN                  NaN   
1                   NaN                   NaN                  NaN   
2                   NaN                   NaN                  NaN   
3                   NaN                   NaN                  NaN   
4                   NaN                   NaN                  NaN   

  trafficSourceCampaign trafficSourceCampaignCode trafficSourceIsTrueDirect  \
0                   NaN                       NaN                       NaN   
1                   NaN                       NaN                       NaN   
2                   NaN                       NaN                       NaN   
3                   NaN                       NaN                       NaN   
4                   NaN                       NaN                      True   

  trafficSourceKeyword trafficSourceMedium trafficSourceReferralPath  \
0              

### Type of vars

In [8]:
df.dtypes

channelGrouping               object
date                           int64
fullVisitorId                 object
sessionId                     object
socialEngagementType          object
visitId                        int64
visitNumber                    int64
visitStartTime                 int64
deviceBrowser                 object
deviceCategory                object
deviceIsMobile                  bool
deviceOS                      object
geoCity                       object
geoContinent                  object
geoCountry                    object
geoMetro                      object
geoDomain                     object
geoRegion                     object
geoSubContinent               object
totalsBounces                float64
totalsHits                     int64
totalsNewVisits              float64
totalsPageviews              float64
totalsTransactionRevenue     float64
totalsVisits                   int64
trafficSourceAdContent        object
adwordsClickAdNetworkType     object
a

The categories of the diferent vars are:

**CATEGORICAL:**

* channelGrouping: Channel of arrival of the visit
* fullVisitorId: Visitor ID
* sessionId: Session ID (contains Visitor ID)
* socialEngagementType: Type of engagement
* deviceBrowser: Name of the Browser
* deviceCategory: Name of the device category 
* deviceOS: The OS of the device
* geoCity: City of the visit
* geoContinent: Continent of the visit
* geoCountry: Country of the visit
* geoMetro: Metro of the visit
* geoDomain: Domain of the visit
* geoRegion: Region of the visit
* geoSubContinent: Subcontinent of the visit   
* trafficSourceAdContent: Source of the Ads
* adwordsClickAdNetworkType: Ad Source
* adwordsClickGclId: Ad Click ID
* adwordsClickInfo.slot: Place of the ad
* trafficSourceCampaign: Name of the souce campaign
* trafficSourceKeyword: Name of the source Keyword
* trafficSourceMedium: Name of the source Medium
* trafficSourceReferralPath: Referral Path
* trafficSourceSource: Name of the source
    
    
**BOOLEAN:**
* deviceIsMobile: is the device mobile
* totalsBounces: Is bounce 
* totalsNewVisits: Is new visit 
* adwordsClickIsVideoAd: Is from ad video 
* trafficSourceIsTrueDirect: Is it a true direct visit

**ORDINAL:**
* visitId: Visit ID integer (is the date in unix time)   
* visitNumber: The number of visit of one user

**NUMERICAL:**

**INTEGER:**
* totalsHits: number of hits
* totalsPageviews: number of pageviews
* totalsTransactionRevenue: (TARGET) logaritm if the revenue
* totalsVisits: Number of visits
* adwordsClickInfoPage: click from ad in page
   
**DATE:**
* date: Date of the visit
* visitStartTime: unix time of the visit


### NaN

In [9]:
df.isnull().sum()

channelGrouping                   0
date                              0
fullVisitorId                     0
sessionId                         0
socialEngagementType              0
visitId                           0
visitNumber                       0
visitStartTime                    0
deviceBrowser                     8
deviceCategory                    0
deviceIsMobile                    0
deviceOS                       4695
geoCity                      542491
geoContinent                   1468
geoCountry                     1468
geoMetro                     709995
geoDomain                    244881
geoRegion                    536056
geoSubContinent                1468
totalsBounces                453023
totalsHits                        0
totalsNewVisits              200593
totalsPageviews                 100
totalsTransactionRevenue     892138
totalsVisits                      0
trafficSourceAdContent       892707
adwordsClickAdNetworkType    882193
adwordsClickGclId           

In [10]:
#Show the columns percentage of nulls higher that 10% with a function
percentNulls(df)

**geoCity** % Nulls is 60.03
**geoMetro** % Nulls is 78.57
**geoDomain** % Nulls is 27.1
**geoRegion** % Nulls is 59.32
**totalsBounces** % Nulls is 50.13
**totalsNewVisits** % Nulls is 22.2
**totalsTransactionRevenue** % Nulls is 98.73
**trafficSourceAdContent** % Nulls is 98.79
**adwordsClickAdNetworkType** % Nulls is 97.63
**adwordsClickGclId** % Nulls is 97.61
**adwordsClickIsVideoAd** % Nulls is 97.63
**adwordsClickInfoPage** % Nulls is 97.63
**adwordsClickInfoSlot** % Nulls is 97.63
**trafficSourceCampaign** % Nulls is 95.76
**trafficSourceCampaignCode** % Nulls is 100.0
**trafficSourceIsTrueDirect** % Nulls is 69.68
**trafficSourceKeyword** % Nulls is 96.2
**trafficSourceReferralPath** % Nulls is 63.38


The column **Traffic Source Campaign** code is almost empty (has only one value that seems an error). I drop the column.

In [11]:
df.loc[df['trafficSourceCampaignCode'] == df['trafficSourceCampaignCode']]

channelGrouping      date       fullVisitorId  \
61493         (Other)  20160831  546985073727768157   

                           sessionId  socialEngagementType     visitId  \
61493  546985073727768157_1472658560  Not Socially Engaged  1472658560   

       visitNumber  visitStartTime deviceBrowser deviceCategory  \
61493            3      1472658560        Chrome        desktop   

       deviceIsMobile   deviceOS geoCity geoContinent   geoCountry geoMetro  \
61493           False  Macintosh     NaN         Asia  Philippines      NaN   

      geoDomain geoRegion geoSubContinent  totalsBounces  totalsHits  \
61493       NaN       NaN  Southeast Asia            1.0           1   

       totalsNewVisits  totalsPageviews  totalsTransactionRevenue  \
61493              NaN              1.0                       NaN   

       totalsVisits trafficSourceAdContent adwordsClickAdNetworkType  \
61493             1                    NaN                       NaN   

      adwordsClickGclId adwordsClickIsVideoAd  adwordsClickInfoPage  \
61493               NaN                   NaN                   NaN   

      adwordsClickInfoSlot trafficSourceCampaign trafficSourceCampaignCode  \
61493                  NaN                   NaN             11251kjhkvahf   

      trafficSourceIsTrueDirect trafficSourceKeyword trafficSourceMedium  \
61493                       NaN                  NaN                 NaN   

      trafficSourceReferralPath trafficSourceSource  
61493                       NaN                 NaN

In [12]:
df.drop(columns='trafficSourceCampaignCode', inplace=True)

In [13]:
df.head()

channelGrouping      date        fullVisitorId  \
0  Organic Search  20160902  1131660440785968503   
1  Organic Search  20160902   377306020877927890   
2  Organic Search  20160902  3895546263509774583   
3  Organic Search  20160902  4763447161404445595   
4  Organic Search  20160902    27294437909732085   

                        sessionId  socialEngagementType     visitId  \
0  1131660440785968503_1472830385  Not Socially Engaged  1472830385   
1   377306020877927890_1472880147  Not Socially Engaged  1472880147   
2  3895546263509774583_1472865386  Not Socially Engaged  1472865386   
3  4763447161404445595_1472881213  Not Socially Engaged  1472881213   
4    27294437909732085_1472822600  Not Socially Engaged  1472822600   

   visitNumber  visitStartTime deviceBrowser deviceCategory  deviceIsMobile  \
0            1      1472830385        Chrome        desktop           False   
1            1      1472880147       Firefox        desktop           False   
2            1      1472865386        Chrome        desktop           False   
3            1      1472881213    UC Browser        desktop           False   
4            2      1472822600        Chrome         mobile            True   

    deviceOS geoCity geoContinent      geoCountry geoMetro        geoDomain  \
0    Windows   Izmir         Asia          Turkey      NaN     ttnet.com.tr   
1  Macintosh     NaN      Oceania       Australia      NaN      dodo.net.au   
2    Windows  Madrid       Europe           Spain      NaN  unknown.unknown   
3      Linux     NaN         Asia       Indonesia      NaN  unknown.unknown   
4    Android     NaN       Europe  United Kingdom      NaN  unknown.unknown   

             geoRegion  geoSubContinent  totalsBounces  totalsHits  \
0                Izmir     Western Asia            1.0           1   
1                  NaN      Australasia            1.0           1   
2  Community of Madrid  Southern Europe            1.0           1   
3                  NaN   Southeast Asia            1.0           1   
4                  NaN  Northern Europe            1.0           1   

   totalsNewVisits  totalsPageviews  totalsTransactionRevenue  totalsVisits  \
0              1.0              1.0                       NaN             1   
1              1.0              1.0                       NaN             1   
2              1.0              1.0                       NaN             1   
3              1.0              1.0                       NaN             1   
4              NaN              1.0                       NaN             1   

  trafficSourceAdContent adwordsClickAdNetworkType adwordsClickGclId  \
0                    NaN                       NaN               NaN   
1                    NaN                       NaN               NaN   
2                    NaN                       NaN               NaN   
3                    NaN                       NaN               NaN   
4                    NaN                       NaN               NaN   

  adwordsClickIsVideoAd  adwordsClickInfoPage adwordsClickInfoSlot  \
0                   NaN                   NaN                  NaN   
1                   NaN                   NaN                  NaN   
2                   NaN                   NaN                  NaN   
3                   NaN                   NaN                  NaN   
4                   NaN                   NaN                  NaN   

  trafficSourceCampaign trafficSourceIsTrueDirect trafficSourceKeyword  \
0                   NaN                       NaN                  NaN   
1                   NaN                       NaN                  NaN   
2                   NaN                       NaN                  NaN   
3                   NaN                       NaN      google + online   
4                   NaN                      True                  NaN   

  trafficSourceMedium trafficSourceReferralPath trafficSourceSource  
0             organic                       NaN

The rest of the columns seems to be valuable eventhough to keep them. If they have many Nans so I will treat it when I study each var.

### No variance

The column **socialEngagementType** only has one value. So it doen't give us any information about the visit. I drop the column.

In [14]:
df.socialEngagementType.value_counts()

Not Socially Engaged    903653
Name: socialEngagementType, dtype: int64

In [15]:
df.drop(columns='socialEngagementType', inplace=True)

The column **totalsVisits** only has one value. So it doesn't give us any information about the visit. I drop the column.

In [16]:
df.totalsVisits.value_counts()

1    903653
Name: totalsVisits, dtype: int64

In [17]:
df.drop(columns='totalsVisits', inplace=True)

In [18]:
df.head()

channelGrouping      date        fullVisitorId  \
0  Organic Search  20160902  1131660440785968503   
1  Organic Search  20160902   377306020877927890   
2  Organic Search  20160902  3895546263509774583   
3  Organic Search  20160902  4763447161404445595   
4  Organic Search  20160902    27294437909732085   

                        sessionId     visitId  visitNumber  visitStartTime  \
0  1131660440785968503_1472830385  1472830385            1      1472830385   
1   377306020877927890_1472880147  1472880147            1      1472880147   
2  3895546263509774583_1472865386  1472865386            1      1472865386   
3  4763447161404445595_1472881213  1472881213            1      1472881213   
4    27294437909732085_1472822600  1472822600            2      1472822600   

  deviceBrowser deviceCategory  deviceIsMobile   deviceOS geoCity  \
0        Chrome        desktop           False    Windows   Izmir   
1       Firefox        desktop           False  Macintosh     NaN   
2        Chrome        desktop           False    Windows  Madrid   
3    UC Browser        desktop           False      Linux     NaN   
4        Chrome         mobile            True    Android     NaN   

  geoContinent      geoCountry geoMetro        geoDomain            geoRegion  \
0         Asia          Turkey      NaN     ttnet.com.tr                Izmir   
1      Oceania       Australia      NaN      dodo.net.au                  NaN   
2       Europe           Spain      NaN  unknown.unknown  Community of Madrid   
3         Asia       Indonesia      NaN  unknown.unknown                  NaN   
4       Europe  United Kingdom      NaN  unknown.unknown                  NaN   

   geoSubContinent  totalsBounces  totalsHits  totalsNewVisits  \
0     Western Asia            1.0           1              1.0   
1      Australasia            1.0           1              1.0   
2  Southern Europe            1.0           1              1.0   
3   Southeast Asia            1.0           1              1.0   
4  Northern Europe            1.0           1              NaN   

   totalsPageviews  totalsTransactionRevenue trafficSourceAdContent  \
0              1.0                       NaN                    NaN   
1              1.0                       NaN                    NaN   
2              1.0                       NaN                    NaN   
3              1.0                       NaN                    NaN   
4              1.0                       NaN                    NaN   

  adwordsClickAdNetworkType adwordsClickGclId adwordsClickIsVideoAd  \
0                       NaN               NaN                   NaN   
1                       NaN               NaN                   NaN   
2                       NaN               NaN                   NaN   
3                       NaN               NaN                   NaN   
4                       NaN               NaN                   NaN   

   adwordsClickInfoPage adwordsClickInfoSlot trafficSourceCampaign  \
0                   NaN                  NaN                   NaN   
1                   NaN                  NaN                   NaN   
2                   NaN                  NaN                   NaN   
3                   NaN                  NaN                   NaN   
4                   NaN                  NaN                   NaN   

  trafficSourceIsTrueDirect trafficSourceKeyword trafficSourceMedium  \
0                       NaN                  NaN             organic   
1                       NaN                  NaN             organic   
2                       NaN                  NaN             organic   
3                       NaN      google + online             organic   
4                      True                  NaN             organic   

  trafficSourceReferralPath trafficSourceSource  
0                       NaN              google  
1                       NaN              google  
2                       NaN              google  
3            

### Vars Preprocessing

In [19]:
df.columns

Index(['channelGrouping', 'date', 'fullVisitorId', 'sessionId', 'visitId',
       'visitNumber', 'visitStartTime', 'deviceBrowser', 'deviceCategory',
       'deviceIsMobile', 'deviceOS', 'geoCity', 'geoContinent', 'geoCountry',
       'geoMetro', 'geoDomain', 'geoRegion', 'geoSubContinent',
       'totalsBounces', 'totalsHits', 'totalsNewVisits', 'totalsPageviews',
       'totalsTransactionRevenue', 'trafficSourceAdContent',
       'adwordsClickAdNetworkType', 'adwordsClickGclId',
       'adwordsClickIsVideoAd', 'adwordsClickInfoPage', 'adwordsClickInfoSlot',
       'trafficSourceCampaign', 'trafficSourceIsTrueDirect',
       'trafficSourceKeyword', 'trafficSourceMedium',
       'trafficSourceReferralPath', 'trafficSourceSource'],
      dtype='object')

#### channelGrouping

This var has no nulls and no strange values. But we will change ('Other') for a simpler value

In [20]:
df.channelGrouping.isnull().sum()

0

In [21]:
df.channelGrouping.unique()

array(['Organic Search', 'Referral', 'Paid Search', 'Affiliates',
       'Direct', 'Display', 'Social', '(Other)'], dtype=object)

In [22]:
df.channelGrouping.value_counts()

Organic Search    381561
Social            226117
Direct            143026
Referral          104838
Paid Search        25326
Affiliates         16403
Display             6262
(Other)              120
Name: channelGrouping, dtype: int64

In [23]:
df.channelGrouping.replace('(Other)', 'Other', inplace=True)

In [24]:
df.channelGrouping.unique()

array(['Organic Search', 'Referral', 'Paid Search', 'Affiliates',
       'Direct', 'Display', 'Social', 'Other'], dtype=object)

#### date

The var date has one year of data. We will transform the column into a datetime

In [25]:
df.date.isnull().sum()

0

In [26]:
len(df.date.unique())

366

In [27]:
df.date = df.date.apply(lambda x: datetime.strptime(str(x), '%Y%m%d').strftime('%Y-%m-%d'))

In [28]:
df.date.dtype

dtype('O')

#### 'fullVisitorId'

The fullvisitor ID might not be usefull for the ML problem, but I keep the column dor the moment as a referce of the user.

In [29]:
df.fullVisitorId.isnull().sum()

0

In [30]:
df.fullVisitorId.unique()

array(['1131660440785968503', '377306020877927890', '3895546263509774583',
       ..., '5123779100307500332', '7231728964973959842',
       '5744576632396406899'], dtype=object)

In [31]:
df.fullVisitorId.value_counts().head()

1957458976293878100    278
3608475193341679870    201
1856749147915772585    199
0824839726118485274    177
3269834865385146569    155
Name: fullVisitorId, dtype: int64

#### sessionId

The var sessionID is extremely variable so I wont keep the column

In [32]:
df.sessionId.isnull().sum()

0

In [33]:
df.sessionId.unique()

array(['1131660440785968503_1472830385', '377306020877927890_1472880147',
       '3895546263509774583_1472865386', ...,
       '5744576632396406899_1483526434', '2709355455991750775_1483592857',
       '0814900163617805053_1483574474'], dtype=object)

In [34]:
df.sessionId.value_counts().head()

6175566964540854873_1489560724    2
3582515949623937277_1494744426    2
4259892450612050951_1486972634    2
0757525465947006821_1500619889    2
8348371514013904251_1485416956    2
Name: sessionId, dtype: int64

In [35]:
df.drop(columns='sessionId', inplace=True)

#### visitId

In [36]:
df.visitId.isnull().sum()

0

In [37]:
len(df.visitId.unique())

886303

In [38]:
df.visitId.value_counts().head()

1493146175    8
1484649802    6
1478345904    6
1481369525    6
1494374199    5
Name: visitId, dtype: int64

In [39]:
df.drop(columns='visitId', inplace=True)

#### visitNumber

We will keep wisit number as it is

In [40]:
df.visitNumber.isnull().sum()

0

In [41]:
df.visitNumber.unique()

array([  1,   2,   3,   5,  11,   4,  57,   6,  56,   7,  20,   8,  15,
         9,  25,  24,  14,  89, 136,  13,  85,  10, 105,  22,  21,  48,
        18,  26,  17,  83,  38,  84,  27,  42, 100,  31,  16,  30,  59,
        50,  19,  51,  29, 160,  52,  12,  63,  23,  47,  49,  28,  34,
       178,  88,  33, 317,  93, 140,  35,  41,  91,  92,  74, 309,  43,
        61,  46,  45,  32, 108,  86, 195,  36, 236,  72, 162, 235,  90,
        76,  77,  94,  96,  73,  78,  97,  87, 304, 106, 107, 389,  68,
        98, 132,  58, 266, 267, 221,  39, 121, 143, 142, 174, 175, 189,
       191,  55, 190, 104, 245, 204,  37,  82, 137, 206, 101,  62, 110,
       156, 158, 157, 159, 138, 109, 194, 193, 147, 254,  71,  53, 144,
       145, 146,  80, 253,  99, 134, 135, 102,  44, 130,  95,  75, 103,
       315,  70,  69, 117, 163, 154, 153, 283,  65, 262, 263, 295, 297,
       298, 219,  64, 296, 155, 141, 169, 170,  60, 207,  54, 187, 133,
       118, 264,  67,  66, 126,  40, 122, 325, 326, 197, 167, 19

In [42]:
df.visitNumber.value_counts().head()

1    703060
2     92548
3     35843
4     19157
5     11615
Name: visitNumber, dtype: int64

In [43]:
df.visitNumber.dtype #check the type of the var

dtype('int64')

#### visitStartTime

This var is the visitStartTime in unix, I will keep the column by the moment

In [44]:
df.visitStartTime.isnull().sum()

0

In [45]:
df.visitStartTime.unique()

array([1472830385, 1472880147, 1472865386, ..., 1483526434, 1483592864,
       1483574474])

In [46]:
df.visitStartTime.value_counts().head()

1493146175    8
1478345904    6
1484649802    6
1481369525    6
1494374199    5
Name: visitStartTime, dtype: int64

In [47]:
df.visitStartTime.unique()

array([1472830385, 1472880147, 1472865386, ..., 1483526434, 1483592864,
       1483574474])

#### deviceBrowser

This var has a few nulls, that we will fill with Unknown.

In [48]:
df.deviceBrowser.isnull().sum()

8

In [49]:
df.deviceBrowser.unique()

array(['Chrome', 'Firefox', 'UC Browser', 'Internet Explorer', 'Safari',
       'Edge', 'Opera Mini', 'Opera', 'BlackBerry', 'Safari (in-app)',
       'Coc Coc', 'Mozilla Compatible Agent', 'ADM', 'MRCHROME',
       'Amazon Silk', 'YaBrowser', 'Android Webview', 'Puffin',
       'Nokia Browser', 'Maxthon', 'Nintendo Browser', 'Android Browser',
       'Lunascape', 'IE with Chrome Frame', 'ThumbSniper',
       'LYF_LS_4002_12', 'Mozilla', 'osee2unifiedRelease', 'NokiaE52-1',
       'Iron', '[Use default User-agent string] LIVRENPOCHE', nan,
       'LYF_LS_4002_11', 'M5', 'Android Runtime', 'Apple-iPhone7C2',
       'SeaMonkey', 'Konqueror', 'Seznam', 'Changa 99695759', 'no-ua',
       'MQQBrowser', 'Nichrome', 'HTC802t_TD', 'DASH_JR_3G', 'DoCoMo',
       'subjectAgent: NoticiasBoom', 'YE', 'User Agent', '0',
       'Hisense M20-M_LTE', 'Reddit', 'TCL P500M', 'CSM Click'],
      dtype=object)

In [50]:
df.deviceBrowser.value_counts().head()

Chrome               620364
Safari               182245
Firefox               37069
Internet Explorer     19375
Edge                  10205
Name: deviceBrowser, dtype: int64

In [51]:
df.deviceBrowser.fillna('Unknown', inplace=True)

In [52]:
df.deviceBrowser.isnull().sum()

0

#### deviceCategory

In [53]:
df.deviceCategory.isnull().sum()

0

In [54]:
df.deviceCategory.unique()

array(['desktop', 'mobile', 'tablet'], dtype=object)

In [55]:
df.deviceCategory.value_counts()

desktop    664479
mobile     208725
tablet      30449
Name: deviceCategory, dtype: int64

#### deviceIsMobile

In [56]:
df.deviceIsMobile.isnull().sum()

0

In [57]:
df.deviceIsMobile.unique()

array([False,  True])

In [58]:
df.deviceIsMobile.value_counts()

False    664530
True     239123
Name: deviceIsMobile, dtype: int64

#### deviceOS

The column **deviceOS** has many valuable data, so we will keep the column and change the NaN for Unknown.

In [59]:
df.deviceOS.isnull().sum()

4695

In [60]:
df.deviceOS.unique()

array(['Windows', 'Macintosh', 'Linux', 'Android', 'iOS', 'Chrome OS',
       'BlackBerry', nan, 'Samsung', 'Windows Phone', 'Xbox',
       'Nintendo Wii', 'Firefox OS', 'Nintendo WiiU', 'FreeBSD', 'Nokia',
       'NTT DoCoMo', 'Nintendo 3DS', 'SunOS', 'OpenBSD'], dtype=object)

In [61]:
df.deviceOS.fillna('Unknown', inplace=True)

In [62]:
df.deviceOS.isnull().sum()

0

#### geoCity

The column **geoCity** has many valuable data, so we will keep the column and change the NaN for Unknown.

In [63]:
df.geoCity.isnull().sum()

542491

In [64]:
df.geoCity.unique()[0:10]

array(['Izmir', nan, 'Madrid', 'Brisbane', 'Karachi', 'Paris',
       'Singapore', 'Buenos Aires', 'Bangkok', 'Jakarta'], dtype=object)

In [65]:
df.geoCity.fillna('Unknown', inplace=True)

In [66]:
df.geoCity.isnull().sum()

0

#### geoMetro

The column **geoMetro** has data that can be used to complete other geo colums, so we will keep the column and change the NaN for Unknown.

In [67]:
df.geoMetro.isnull().sum()

709995

In [68]:
df.geoMetro.unique()[0:10]

array([nan, 'London', 'San Francisco-Oakland-San Jose CA', 'New York NY',
       'Washington DC (Hagerstown MD)', 'Los Angeles CA',
       'Seattle-Tacoma WA', 'Chicago IL', 'Boston MA-Manchester NH',
       'Detroit MI'], dtype=object)

In [69]:
df.geoMetro.fillna('Unknown', inplace=True)

In [70]:
df.geoMetro.isnull().sum()

0

#### geoDomain

The column **geoDomain** has data that can be used to complete other geo colums, so we will keep the column and change the NaN and unknown.unknown for Unknown.

In [71]:
df.geoDomain.isnull().sum()

244881

In [72]:
df.geoDomain.unique()[0:10]

array(['ttnet.com.tr', 'dodo.net.au', 'unknown.unknown', 'fastwebnet.it',
       'bigpond.net.au', 'spar.at', 'chello.nl', 'airtelbroadband.in',
       'wanadoo.fr', 'cabotelecom.com.br'], dtype=object)

In [73]:
df.geoDomain.value_counts().head(10)

unknown.unknown          146034
comcast.net               28743
rr.com                    14827
verizon.net               13637
ttnet.com.tr              13228
comcastbusiness.net        9985
hinet.net                  7919
virginm.net                6414
3bb.co.th                  6046
prod-infinitum.com.mx      5960
Name: geoDomain, dtype: int64

In [74]:
df.geoDomain.fillna('Unknown', inplace=True)

In [75]:
df.geoDomain.replace('unknown.unknown', 'Unknown', inplace=True)

In [76]:
df.geoDomain.value_counts().head(10)

Unknown                  390915
comcast.net               28743
rr.com                    14827
verizon.net               13637
ttnet.com.tr              13228
comcastbusiness.net        9985
hinet.net                  7919
virginm.net                6414
3bb.co.th                  6046
prod-infinitum.com.mx      5960
Name: geoDomain, dtype: int64

In [77]:
df.geoDomain.isnull().sum()

0

#### geoRegion

The column **geoRegion** also can be used to fill info from the other geo columns.

In [78]:
df.geoRegion.isnull().sum()

536056

In [79]:
df.geoRegion.unique()[0:10]

array(['Izmir', nan, 'Community of Madrid', 'Queensland', 'Sindh',
       'Ile-de-France', 'Buenos Aires', 'Bangkok', 'Jakarta', 'Karnataka'],
      dtype=object)

In [80]:
df.geoRegion.value_counts().head(10)

California     107495
New York        26433
England         13198
Texas            8749
Bangkok          7709
Washington       7642
Illinois         7585
Ho Chi Minh      7250
Istanbul         6330
Maharashtra      6184
Name: geoRegion, dtype: int64

In [81]:
df.geoRegion.fillna('Unknown', inplace=True)

In [82]:
df.geoRegion.isnull().sum()

0

#### geoSubContinent

In [83]:
df.geoSubContinent.isnull().sum()

1468

In [84]:
df.geoSubContinent.unique()

array(['Western Asia', 'Australasia', 'Southern Europe', 'Southeast Asia',
       'Northern Europe', 'Southern Asia', 'Western Europe',
       'South America', 'Eastern Asia', 'Eastern Europe',
       'Northern America', 'Western Africa', 'Central America',
       'Eastern Africa', nan, 'Caribbean', 'Southern Africa',
       'Northern Africa', 'Central Asia', 'Middle Africa', 'Melanesia',
       'Micronesian Region', 'Polynesia'], dtype=object)

In [85]:
df.geoSubContinent.value_counts().head(10)

Northern America    390657
Southeast Asia       77800
Southern Asia        59321
Western Europe       59114
Northern Europe      58168
Eastern Asia         46919
Eastern Europe       45249
South America        41731
Western Asia         38443
Southern Europe      35780
Name: geoSubContinent, dtype: int64

In [86]:
df.geoSubContinent.fillna('Unknown', inplace=True)

In [87]:
df.geoSubContinent.isnull().sum()

0

#### totalsBounces

The var **totalsBounces** has many "False Nans". As a Boolean, 1 is True and nan is False. I will replace nan with 0.

In [88]:
df.totalsBounces.isnull().sum()

453023

In [89]:
df.totalsBounces.unique()

array([ 1., nan])

In [90]:
df.totalsBounces.fillna(0, inplace=True)

In [91]:
df.totalsBounces.value_counts()

0.0    453023
1.0    450630
Name: totalsBounces, dtype: int64

In [92]:
df.totalsBounces.isnull().sum()

0

#### totalsHits

The var **totalsHits** has no nulls, and has the correct dtype.

In [93]:
df.totalsHits.isnull().sum()

0

In [94]:
df.totalsHits.unique()[0:50]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51])

In [95]:
df.totalsHits.value_counts().head()

1    446754
2    137952
3     70402
4     42444
5     30939
Name: totalsHits, dtype: int64

In [96]:
df.totalsHits.isnull().sum()

0

#### totalsNewVisits

The var **totalsNewVisits** has many False Nans. As a Boolean, 1 is True and nan is False. I will replace nan with 0.

In [97]:
df.totalsNewVisits.isnull().sum()

200593

In [98]:
df.totalsNewVisits.unique()

array([ 1., nan])

In [99]:
df.totalsNewVisits.fillna(0, inplace=True)

In [100]:
df.totalsNewVisits.value_counts().head()

1.0    703060
0.0    200593
Name: totalsNewVisits, dtype: int64

In [101]:
df.totalsNewVisits.isnull().sum()

0

#### totalsPageviews

The column **totalsPageviews** has 100 null values that I cannot infere from other columns, as the percentage is so small, I drop the rows.

In [102]:
df.totalsPageviews.isnull().sum()

100

In [103]:
df.totalsPageviews.unique()

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  20.,  19.,  21.,  25.,
        22.,  26.,  23.,  24.,  30.,  27.,  29.,  28.,  32.,  31.,  34.,
        33.,  38.,  35.,  40.,  36.,  37.,  39.,  43.,  45.,  47.,  52.,
        44.,  50.,  46.,  49.,  51.,  56.,  59.,  71.,  57.,  82.,  84.,
        92.,  90.,  41.,  79., 138.,  48.,  69., 112.,  42.,  65.,  60.,
        63.,  68.,  58.,  74., 165.,  53.,  54.,  55.,  61.,  70.,  80.,
        78.,  72., 188.,  73.,  62.,  75.,  86., 197., 148.,  67., 102.,
        64., 103., 144.,  nan,  81., 119., 104., 128.,  87., 111.,  66.,
        83., 135.,  94.,  91.,  99.,  77., 118., 202., 127.,  93., 106.,
       155., 117.,  76.,  89.,  85., 143., 105., 115.,  95., 110., 137.,
       120., 116., 208., 126., 400., 101., 108., 333.,  97.,  96.,  98.,
       125., 113., 327., 154., 121., 183., 123., 141., 224.,  88., 195.,
       343., 156., 193., 100., 150., 122., 145., 17

In [104]:
df.dropna(subset=['totalsPageviews'],inplace=True)

In [105]:
df.totalsPageviews.isnull().sum()

0

In [106]:
df.totalsPageviews.value_counts().head(10)

1.0     452522
2.0     143770
3.0      73835
4.0      45192
5.0      33411
6.0      24688
7.0      19476
8.0      15272
9.0      12585
10.0     10104
Name: totalsPageviews, dtype: int64

In [107]:
df.totalsPageviews.isnull().sum()

0

#### trafficSourceAdContent

There are many nans in the **adwordsClickAdNetworkType** column, for all the visits that do not come from an Ad. I change the Nan value for a NoAd.

In [108]:
df.trafficSourceAdContent.isnull().sum()

892608

In [109]:
df.trafficSourceAdContent.unique()

array([nan, 'Full auto ad IMAGE ONLY', 'First Full Auto Template Test Ad',
       '{KeyWord:Google Brand Items}', 'Display Ad created 3/11/14',
       'Ad from 11/7/16', 'Display Ad created 3/11/15',
       'Ad from 12/13/16', 'Ad from 11/3/16', 'Google Online Store',
       'Google Merchandise Collection', '{KeyWord:Want Google Stickers?}',
       '{KeyWord:Google Merchandise}', 'Display Ad created 11/17/14',
       '{KeyWord:Google Drinkware}', "{KeyWord:Google Men's T-Shirts}",
       '{KeyWord:Google Branded Gear}',
       '{KeyWord:Google Branded Apparel}', 'Google Paraphernalia',
       'Swag with Google Logos', '{KeyWord:Google Branded Kit}',
       'Want Google Sunglasses', '{KeyWord:Looking for Google Bags?}',
       'Full auto ad TEXT ONLY', 'Google Merchandise', 'google store',
       'LeEco_1a', 'Full auto ad TEXT/NATIVE',
       '{KeyWord:Want Google Pet Toys?}', 'Google Store',
       "Men's-Outerwear Google Apparel", '20% discount',
       'Full auto ad with Primary Colo

In [110]:
df.trafficSourceAdContent.fillna('NoAd', inplace=True)

In [111]:
df.trafficSourceAdContent.value_counts().head(10)

NoAd                             892608
Google Merchandise Collection      5122
Google Online Store                1245
Display Ad created 3/11/14          966
Full auto ad IMAGE ONLY             822
Ad from 12/13/16                    610
Ad from 11/3/16                     489
Display Ad created 3/11/15          392
{KeyWord:Google Brand Items}        251
{KeyWord:Google Merchandise}        155
Name: trafficSourceAdContent, dtype: int64

In [112]:
df.trafficSourceAdContent.isnull().sum()

0

#### adwordsClickAdNetworkType

There are many nans in the **adwordsClickAdNetworkType** column, for all the visits that do not come from an AdWord Ad. I change the Nan value for a NoAdWords.

In [113]:
df.adwordsClickAdNetworkType.isnull().sum()

882093

In [114]:
df.adwordsClickAdNetworkType.unique()

array([nan, 'Google Search', 'Search partners'], dtype=object)

In [115]:
df.adwordsClickAdNetworkType.fillna('NoAdWords', inplace=True)

In [116]:
df.adwordsClickAdNetworkType.value_counts()

NoAdWords          882093
Google Search       21453
Search partners         7
Name: adwordsClickAdNetworkType, dtype: int64

In [117]:
df.adwordsClickAdNetworkType.isnull().sum()

0

#### adwordsClickGclId

The **adwordsClickGclId** var is the unique ID for the Google Search clicks. As I cannot use the Ids I will modify the values for a boolean. Click, No Click.


In [118]:
df.adwordsClickGclId.isnull().sum()

881992

In [119]:
df[['adwordsClickGclId','adwordsClickAdNetworkType','trafficSourceAdContent']].loc[df['adwordsClickGclId']==df['adwordsClickGclId']].head()


adwordsClickGclId  \
102  Cj0KEQjwxqS-BRDRgPLp0q2t0IUBEiQAgfMXRBVDYwnFaw...   
271  Cj0KEQjwxqS-BRDRgPLp0q2t0IUBEiQAgfMXRAq0D2zir1...   
295  Cj0KEQjwxqS-BRDRgPLp0q2t0IUBEiQAgfMXRMbhgNCALe...   
305  Cj0KEQjwxqS-BRDRgPLp0q2t0IUBEiQAgfMXRBRI7rtb79...   
400  Cj0KEQjwxqS-BRDRgPLp0q2t0IUBEiQAgfMXRDKcQOTkfR...   

    adwordsClickAdNetworkType trafficSourceAdContent  
102             Google Search                   NoAd  
271             Google Search                   NoAd  
295             Google Search                   NoAd  
305             Google Search                   NoAd  
400             Google Search                   NoAd

In [120]:
df.adwordsClickGclId = df.adwordsClickGclId.apply(lambda x: 1 if x == x else 0)

In [121]:
df.head()

channelGrouping        date        fullVisitorId  visitNumber  \
0  Organic Search  2016-09-02  1131660440785968503            1   
1  Organic Search  2016-09-02   377306020877927890            1   
2  Organic Search  2016-09-02  3895546263509774583            1   
3  Organic Search  2016-09-02  4763447161404445595            1   
4  Organic Search  2016-09-02    27294437909732085            2   

   visitStartTime deviceBrowser deviceCategory  deviceIsMobile   deviceOS  \
0      1472830385        Chrome        desktop           False    Windows   
1      1472880147       Firefox        desktop           False  Macintosh   
2      1472865386        Chrome        desktop           False    Windows   
3      1472881213    UC Browser        desktop           False      Linux   
4      1472822600        Chrome         mobile            True    Android   

   geoCity geoContinent      geoCountry geoMetro     geoDomain  \
0    Izmir         Asia          Turkey  Unknown  ttnet.com.tr   
1  Unknown      Oceania       Australia  Unknown   dodo.net.au   
2   Madrid       Europe           Spain  Unknown       Unknown   
3  Unknown         Asia       Indonesia  Unknown       Unknown   
4  Unknown       Europe  United Kingdom  Unknown       Unknown   

             geoRegion  geoSubContinent  totalsBounces  totalsHits  \
0                Izmir     Western Asia            1.0           1   
1              Unknown      Australasia            1.0           1   
2  Community of Madrid  Southern Europe            1.0           1   
3              Unknown   Southeast Asia            1.0           1   
4              Unknown  Northern Europe            1.0           1   

   totalsNewVisits  totalsPageviews  totalsTransactionRevenue  \
0              1.0              1.0                       NaN   
1              1.0              1.0                       NaN   
2              1.0              1.0                       NaN   
3              1.0              1.0                       NaN   
4              0.0              1.0                       NaN   

  trafficSourceAdContent adwordsClickAdNetworkType  adwordsClickGclId  \
0                   NoAd                 NoAdWords                  0   
1                   NoAd                 NoAdWords                  0   
2                   NoAd                 NoAdWords                  0   
3                   NoAd                 NoAdWords                  0   
4                   NoAd                 NoAdWords                  0   

  adwordsClickIsVideoAd  adwordsClickInfoPage adwordsClickInfoSlot  \
0                   NaN                   NaN                  NaN   
1                   NaN                   NaN                  NaN   
2                   NaN                   NaN                  NaN   
3                   NaN                   NaN                  NaN   
4                   NaN                   NaN                  NaN   

  trafficSourceCampaign trafficSourceIsTrueDirect trafficSourceKeyword  \
0                   NaN                       NaN                  NaN   
1                   NaN                       NaN                  NaN   
2                   NaN                       NaN                  NaN   
3                   NaN                       NaN      google + online   
4                   NaN                      True                  NaN   

  trafficSourceMedium trafficSourceReferralPath trafficSourceSource  
0             organic                       NaN              google  
1             organic                       NaN              google  
2             organic                       NaN              google  
3             organic                       NaN              google  
4             organic                       NaN              google

In [122]:
df.adwordsClickGclId.unique()

array([0, 1])

In [123]:
df.adwordsClickGclId.value_counts().head()

0    881992
1     21561
Name: adwordsClickGclId, dtype: int64

In [124]:
df.adwordsClickGclId.isnull().sum()

0

#### adwordsClickIsVideoAd

The **adwordsClickIsVideoAd** has a lot of nans, that really mean no Ad. And there are no Trues. So the column do not give me any information. I drop it.

In [125]:
df.adwordsClickIsVideoAd.isnull().sum()

882093

In [126]:
df.adwordsClickIsVideoAd.unique()

array([nan, False], dtype=object)

In [127]:
df.drop(columns='adwordsClickIsVideoAd', inplace=True)

#### adwordsClickInfoPage

The **adwordsClickInfoPage** has many nulls, that means the visit do not come from an add. I will change the Nan for a 0.

In [128]:
df.adwordsClickInfoPage.isnull().sum()

882093

In [129]:
df.adwordsClickInfoPage.unique()

array([nan,  1.,  5.,  3.,  2., 14.,  7.,  9.,  4.])

In [130]:
df.adwordsClickInfoPage.value_counts()

1.0     21362
2.0        73
3.0        10
5.0         7
7.0         3
4.0         2
9.0         2
14.0        1
Name: adwordsClickInfoPage, dtype: int64

In [131]:
df.adwordsClickInfoPage.fillna(0, inplace=True)

In [132]:
df.adwordsClickInfoPage.value_counts()

0.0     882093
1.0      21362
2.0         73
3.0         10
5.0          7
7.0          3
4.0          2
9.0          2
14.0         1
Name: adwordsClickInfoPage, dtype: int64

In [133]:
df.adwordsClickInfoPage.isnull().sum()

0

#### adwordsClickInfoSlot

The var **adwordsClickInfoSlot** tell us if the Adword was on the Top or the Right Column in the Google Search ad.

In [134]:
df.adwordsClickInfoSlot.isnull().sum()

882093

In [135]:
df.adwordsClickInfoSlot.unique()

array([nan, 'Top', 'RHS'], dtype=object)

In [136]:
df[['adwordsClickAdNetworkType','adwordsClickInfoSlot']].loc[df['adwordsClickAdNetworkType'] != 'NoAdWords'].head()


adwordsClickAdNetworkType adwordsClickInfoSlot
102             Google Search                  Top
271             Google Search                  Top
295             Google Search                  Top
305             Google Search                  Top
400             Google Search                  Top

In [137]:
df.adwordsClickInfoSlot.fillna('NoAdwords', inplace=True)

In [138]:
df.adwordsClickInfoSlot.isnull().sum()

0

#### trafficSourceCampaign

The **trafficSourceCampaign** has many Nans that mean there was no campaign behind the visit. I change the Nans for NoCampaign.

In [139]:
df.trafficSourceCampaign.isnull().sum()

865249

In [140]:
df.trafficSourceCampaign.unique()

array([nan, 'AW - Dynamic Search Ads Whole Site', 'Data Share Promo',
       'AW - Electronics', 'test-liyuhz', 'AW - Accessories',
       'Retail (DO NOT EDIT owners nophakun and tianyu)', 'AW - Apparel',
       'All Products', 'Data Share'], dtype=object)

In [141]:
df.trafficSourceCampaign.value_counts()

Data Share Promo                                   16401
AW - Dynamic Search Ads Whole Site                 14244
AW - Accessories                                    7070
test-liyuhz                                          392
AW - Electronics                                      96
Retail (DO NOT EDIT owners nophakun and tianyu)       50
AW - Apparel                                          46
All Products                                           4
Data Share                                             1
Name: trafficSourceCampaign, dtype: int64

In [142]:
df.trafficSourceCampaign.fillna('NoCampaign', inplace=True)

In [143]:
df.trafficSourceCampaign.value_counts()

NoCampaign                                         865249
Data Share Promo                                    16401
AW - Dynamic Search Ads Whole Site                  14244
AW - Accessories                                     7070
test-liyuhz                                           392
AW - Electronics                                       96
Retail (DO NOT EDIT owners nophakun and tianyu)        50
AW - Apparel                                           46
All Products                                            4
Data Share                                              1
Name: trafficSourceCampaign, dtype: int64

In [144]:
df.trafficSourceCampaign.isnull().sum()

0

#### trafficSourceIsTrueDirect

The **trafficSourceIsTrueDirec** var is a boolean weather the visit is Direct or No. I change the Nan for a False.

In [145]:
df.trafficSourceIsTrueDirect.isnull().sum()

629636

In [146]:
df.trafficSourceIsTrueDirect.unique()

array([nan, True], dtype=object)

In [147]:
df[['trafficSourceIsTrueDirect', 'channelGrouping']].loc[df['channelGrouping'] == 'Direct'].head()

trafficSourceIsTrueDirect channelGrouping
139                      True          Direct
147                      True          Direct
185                      True          Direct
297                      True          Direct
332                      True          Direct

In [148]:
df.trafficSourceIsTrueDirect.fillna(False, inplace=True)

In [149]:
df.trafficSourceIsTrueDirect.value_counts()

False    629636
True     273917
Name: trafficSourceIsTrueDirect, dtype: int64

In [150]:
df.trafficSourceIsTrueDirect.isnull().sum()

0

#### trafficSourceKeyword

The **Source Keyword** has many nans that I will change for NoKeyword

In [151]:
df.trafficSourceKeyword.isnull().sum()

869193

In [152]:
df.trafficSourceKeyword.unique()

array([nan, 'google + online', 'www google store', ...,
       'www.google.com bag', 'Google store usar',
       'google shirt buy online'], dtype=object)

In [153]:
df.trafficSourceKeyword.value_counts().head(10)

6qEhsCssdK0z36ri                   11503
(Remarketing/Content targeting)     2297
1hZbAqLCbjwfgOH7                    2264
google merchandise store            2209
Google Merchandise                  1648
google store                        1277
youtube                              568
(User vertical targeting)            489
1X4Me6ZKNV0zg-jV                     467
(automatic matching)                 427
Name: trafficSourceKeyword, dtype: int64

In [154]:
df.trafficSourceKeyword.fillna('NoKeyword', inplace=True)

In [155]:
df.trafficSourceKeyword.value_counts().head(10)

NoKeyword                          869193
6qEhsCssdK0z36ri                    11503
(Remarketing/Content targeting)      2297
1hZbAqLCbjwfgOH7                     2264
google merchandise store             2209
Google Merchandise                   1648
google store                         1277
youtube                               568
(User vertical targeting)             489
1X4Me6ZKNV0zg-jV                      467
Name: trafficSourceKeyword, dtype: int64

In [156]:
df.trafficSourceKeyword.isnull().sum()

0

#### trafficSourceMedium

The Nans of the **trafficSourceMedium** correcpond to the value "other" in channel Grouping. So I will replace the nan for the 'other' value

In [157]:
df.trafficSourceMedium.isnull().sum()

120

In [158]:
df.trafficSourceMedium.unique()

array(['organic', 'referral', 'cpc', 'affiliate', '(none)', 'cpm', nan],
      dtype=object)

In [159]:
df.trafficSourceMedium.value_counts()

organic      381530
referral     330913
(none)       143002
cpc           25325
affiliate     16401
cpm            6262
Name: trafficSourceMedium, dtype: int64

In [160]:
df.loc[df.channelGrouping == 'Other'].count()[0]

120

In [161]:
df.trafficSourceMedium.replace('(none)', 'none', inplace=True)

In [162]:
df.trafficSourceMedium.fillna('other', inplace=True)

In [163]:
df.trafficSourceMedium.value_counts()

organic      381530
referral     330913
none         143002
cpc           25325
affiliate     16401
cpm            6262
other           120
Name: trafficSourceMedium, dtype: int64

In [164]:
df.trafficSourceMedium.isnull().sum()

0

#### trafficSourceReferralPath

The **trafficSourceReferralPath** nans are for visits that do not come from a Referral visit. I change the nans for 'NoReferral' label.

In [165]:
df.trafficSourceReferralPath.isnull().sum()

572654

In [166]:
df.trafficSourceReferralPath.unique()

array([nan, '/', '/corp/google.com/study/incentives/working-with-perks',
       ..., '/BB1QfReObs', '/mail/mu/mp/118/', '/mail/mu/mp/509/'],
      dtype=object)

In [167]:
df.trafficSourceReferralPath.value_counts().head(10)

/                    75502
/yt/about/           71029
/analytics/web/      14618
/yt/about/tr/        14599
/yt/about/vi/        13753
/yt/about/es-419/    12734
/yt/about/pt-BR/     12003
/yt/about/th/        11430
/yt/about/ru/        11193
/yt/about/es/         7090
Name: trafficSourceReferralPath, dtype: int64

In [168]:
df.trafficSourceReferralPath.fillna('NoReferral', inplace=True)

In [169]:
df.trafficSourceReferralPath.value_counts().head(10)

NoReferral           572654
/                     75502
/yt/about/            71029
/analytics/web/       14618
/yt/about/tr/         14599
/yt/about/vi/         13753
/yt/about/es-419/     12734
/yt/about/pt-BR/      12003
/yt/about/th/         11430
/yt/about/ru/         11193
Name: trafficSourceReferralPath, dtype: int64

In [170]:
df.trafficSourceReferralPath.isnull().sum()

0

#### trafficSourceSource

The **trafficSourceSource** Nans means the source is unknown, so I change the values for 'Unknowns'.

In [171]:
df.trafficSourceSource.isnull().sum()

69

In [172]:
df.trafficSourceSource.unique()[0:10]

array(['google', 'baidu', 'googleweblight.com', 'sites.google.com',
       'bing', 'siliconvalley.about.com', 'analytics.google.com',
       'Partners', '(direct)', 'mall.googleplex.com'], dtype=object)

In [173]:
df.trafficSourceSource.value_counts().head()

google                 400756
youtube.com            212589
(direct)               143004
mall.googleplex.com     66397
Partners                16409
Name: trafficSourceSource, dtype: int64

In [174]:
df.trafficSourceSource.replace('(direct)', 'direct', inplace=True)

In [175]:
df.trafficSourceSource.fillna('Unknown', inplace=True)

In [176]:
df.trafficSourceSource.value_counts().head()

google                 400756
youtube.com            212589
direct                 143004
mall.googleplex.com     66397
Partners                16409
Name: trafficSourceSource, dtype: int64

In [177]:
df.trafficSourceSource.isnull().sum()

0

#### totalsTransactionRevenue (TARGET)

The **totalsTransactionRevenue** Nans mean the visit hasn't had a purchase. I change the Nans to a 0 value. The value of this var is the log of the amount in $.

In [178]:
df.totalsTransactionRevenue.isnull().sum()

892038

In [179]:
df.totalsTransactionRevenue.unique()

array([       nan, 3.7860e+07, 3.0667e+08, ..., 3.3526e+08, 3.0750e+07,
       6.9390e+07])

In [180]:
df.totalsTransactionRevenue.value_counts().head()

16990000.0    256
18990000.0    189
33590000.0    187
44790000.0    170
13590000.0    135
Name: totalsTransactionRevenue, dtype: int64

In [181]:
df.totalsTransactionRevenue.fillna(0, inplace=True)

In [182]:
df.totalsTransactionRevenue.value_counts().head()

0.0           892038
16990000.0       256
18990000.0       189
33590000.0       187
44790000.0       170
Name: totalsTransactionRevenue, dtype: int64

In [183]:
df.totalsTransactionRevenue.isnull().sum()

0

**Move the target to the end of the dataframe**

In [184]:
df.columns

Index(['channelGrouping', 'date', 'fullVisitorId', 'visitNumber',
       'visitStartTime', 'deviceBrowser', 'deviceCategory', 'deviceIsMobile',
       'deviceOS', 'geoCity', 'geoContinent', 'geoCountry', 'geoMetro',
       'geoDomain', 'geoRegion', 'geoSubContinent', 'totalsBounces',
       'totalsHits', 'totalsNewVisits', 'totalsPageviews',
       'totalsTransactionRevenue', 'trafficSourceAdContent',
       'adwordsClickAdNetworkType', 'adwordsClickGclId',
       'adwordsClickInfoPage', 'adwordsClickInfoSlot', 'trafficSourceCampaign',
       'trafficSourceIsTrueDirect', 'trafficSourceKeyword',
       'trafficSourceMedium', 'trafficSourceReferralPath',
       'trafficSourceSource'],
      dtype='object')

In [185]:
df = df[['channelGrouping', 'date', 'fullVisitorId', 'visitNumber',
       'visitStartTime', 'deviceBrowser', 'deviceCategory', 'deviceIsMobile',
       'deviceOS', 'geoCity', 'geoContinent', 'geoCountry', 'geoMetro',
       'geoDomain', 'geoRegion', 'geoSubContinent', 'totalsBounces',
       'totalsHits', 'totalsNewVisits', 'totalsPageviews','trafficSourceAdContent',
       'adwordsClickAdNetworkType', 'adwordsClickGclId',
       'adwordsClickInfoPage', 'adwordsClickInfoSlot', 'trafficSourceCampaign',
       'trafficSourceIsTrueDirect', 'trafficSourceKeyword',
       'trafficSourceMedium', 'trafficSourceReferralPath',
       'trafficSourceSource','totalsTransactionRevenue']]

### Describe 

In [186]:
df.shape

(903553, 32)

In [187]:
df.head()

channelGrouping        date        fullVisitorId  visitNumber  \
0  Organic Search  2016-09-02  1131660440785968503            1   
1  Organic Search  2016-09-02   377306020877927890            1   
2  Organic Search  2016-09-02  3895546263509774583            1   
3  Organic Search  2016-09-02  4763447161404445595            1   
4  Organic Search  2016-09-02    27294437909732085            2   

   visitStartTime deviceBrowser deviceCategory  deviceIsMobile   deviceOS  \
0      1472830385        Chrome        desktop           False    Windows   
1      1472880147       Firefox        desktop           False  Macintosh   
2      1472865386        Chrome        desktop           False    Windows   
3      1472881213    UC Browser        desktop           False      Linux   
4      1472822600        Chrome         mobile            True    Android   

   geoCity geoContinent      geoCountry geoMetro     geoDomain  \
0    Izmir         Asia          Turkey  Unknown  ttnet.com.tr   
1  Unknown      Oceania       Australia  Unknown   dodo.net.au   
2   Madrid       Europe           Spain  Unknown       Unknown   
3  Unknown         Asia       Indonesia  Unknown       Unknown   
4  Unknown       Europe  United Kingdom  Unknown       Unknown   

             geoRegion  geoSubContinent  totalsBounces  totalsHits  \
0                Izmir     Western Asia            1.0           1   
1              Unknown      Australasia            1.0           1   
2  Community of Madrid  Southern Europe            1.0           1   
3              Unknown   Southeast Asia            1.0           1   
4              Unknown  Northern Europe            1.0           1   

   totalsNewVisits  totalsPageviews trafficSourceAdContent  \
0              1.0              1.0                   NoAd   
1              1.0              1.0                   NoAd   
2              1.0              1.0                   NoAd   
3              1.0              1.0                   NoAd   
4              0.0              1.0                   NoAd   

  adwordsClickAdNetworkType  adwordsClickGclId  adwordsClickInfoPage  \
0                 NoAdWords                  0                   0.0   
1                 NoAdWords                  0                   0.0   
2                 NoAdWords                  0                   0.0   
3                 NoAdWords                  0                   0.0   
4                 NoAdWords                  0                   0.0   

  adwordsClickInfoSlot trafficSourceCampaign  trafficSourceIsTrueDirect  \
0            NoAdwords            NoCampaign                      False   
1            NoAdwords            NoCampaign                      False   
2            NoAdwords            NoCampaign                      False   
3            NoAdwords            NoCampaign                      False   
4            NoAdwords            NoCampaign                       True   

  trafficSourceKeyword trafficSourceMedium trafficSourceReferralPath  \
0            NoKeyword             organic                NoReferral   
1            NoKeyword             organic                NoReferral   
2            NoKeyword             organic                NoReferral   
3      google + online             organic                NoReferral   
4            NoKeyword             organic                NoReferral   

  trafficSourceSource  totalsTransactionRevenue  
0              google                       0.0  
1              google                       0.0  
2              google                       0.0  
3              google                       0.0  
4              google                       0.0

In [188]:
df.describe().T

count          mean           std           min  \
visitNumber               903553.0  2.264532e+00  9.282528e+00  1.000000e+00   
visitStartTime            903553.0  1.485007e+09  9.021954e+06  1.470035e+09   
totalsBounces             903553.0  4.987311e-01  4.999987e-01  0.000000e+00   
totalsHits                903553.0  4.596866e+00  9.641905e+00  1.000000e+00   
totalsNewVisits           903553.0  7.780894e-01  4.155316e-01  0.000000e+00   
totalsPageviews           903553.0  3.849764e+00  7.025274e+00  1.000000e+00   
adwordsClickGclId         903553.0  2.386246e-02  1.526207e-01  0.000000e+00   
adwordsClickInfoPage      903553.0  2.394326e-02  1.558196e-01  0.000000e+00   
totalsTransactionRevenue  903553.0  1.704461e+06  5.278158e+07  0.000000e+00   

                                   25%           50%           75%  \
visitNumber               1.000000e+00  1.000000e+00  1.000000e+00   
visitStartTime            1.477561e+09  1.483949e+09  1.492758e+09   
totalsBounces             0.000000e+00  0.000000e+00  1.000000e+00   
totalsHits                1.000000e+00  2.000000e+00  4.000000e+00   
totalsNewVisits           1.000000e+00  1.000000e+00  1.000000e+00   
totalsPageviews           1.000000e+00  1.000000e+00  4.000000e+00   
adwordsClickGclId         0.000000e+00  0.000000e+00  0.000000e+00   
adwordsClickInfoPage      0.000000e+00  0.000000e+00  0.000000e+00   
totalsTransactionRevenue  0.000000e+00  0.000000e+00  0.000000e+00   

                                   max  
visitNumber               3.950000e+02  
visitStartTime            1.501657e+09  
totalsBounces             1.000000e+00  
totalsHits                5.000000e+02  
totalsNewVisits           1.000000e+00  
totalsPageviews           4.690000e+02  
adwordsClickGclId         1.000000e+00  
adwordsClickInfoPage      1.400000e+01  
totalsTransactionRevenue  2.312950e+10

### Export Preprocessed dataset

In [189]:
df.to_csv("data/df3.csv", index=False)